[project]
name = "drama-shorts-web"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.11"
dependencies = [
    "django>=6.0.1",
    "django-debug-toolbar>=6.2.0",
    "django-import-export>=4.4.0",
    "django-jazzmin>=3.0.1",
]
